- name: Create WAL-G log folder
  ansible.builtin.file:
    dest: "{{ walg_cluster.value.logfolder }}"
    state: directory
    owner: "{{ walg_user }}"
    group: "{{ walg_group }}"
    mode: "0755"

- name: Install WAL-G cluster configuration
  ansible.builtin.template:
    src: wal-g.default.j2
    dest: "/etc/default/wal-g-{{ walg_cluster.key }}"
    owner: root
    group: root
    mode: "0644"
  vars:
    walg_cluster_defaults: >-
      {{
        walg_bucket_defaults |
        combine({
          'WALG_S3_PREFIX':
            walg_cluster.value.s3_prefix |
            default('s3://' ~ walg_bucket_name)
        }) |
        combine({
          'PGDATA':
            walg_cluster.value.pg_datadir |
            default(walg_pg_datadir),
          'PGBIN':
            walg_cluster.value.pg_bindir |
            default(walg_pg_bindir),
          'PGHOST':
            walg_cluster.value.pg_hostname |
            default(walg_pg_hostname),
          'PGPORT':
            walg_cluster.value.pg_port |
            default(walg_pg_port),
          'PGPASSWORD':
            walg_cluster.value.pg_password |
            default(walg_pg_password)
        }) |
        combine(walg_generic_defaults) |
        combine(walg_retention_defaults) |
        combine(walg_log_defaults) |
        combine({
          'WALG_LOG_FOLDER':
            walg_cluster.value.logfolder |
            default(walg_logfolder),
          'WALG_CLUSTER_NAME': walg_cluster.key
        })
      }}

- name: Configure WAL-G backup cron
  ansible.builtin.cron:
    name: "wal-g backup {{ walg_cluster.key }}"
    minute: "{{ walg_cluster.value.cron.minute | default(walg_cron_minute) }}"
    hour: "{{ walg_cluster.value.cron.hour | default(walg_cron_hour) }}"
    dom: "{{ walg_cluster.value.cron.dom | default(walg_cron_dom) }}"
    dow: "{{ walg_cluster.value.cron.dow | default(walg_cron_dow) }}"
    month: "{{ walg_cluster.value.cron.month | default(walg_cron_month) }}"
    job: "{{ walg_home }}/scripts/backup_locked.sh {{ walg_cluster.key }}"
    user: "{{ walg_user }}"
    cron_file: wal-g
    state: >-
      {{
        'present'
        if walg_cluster.value.cron.enabled | default(walg_cron_enabled)
        else 'absent'
      }}